services:
  postgres-db:
    image: postgres
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: ${DB_USRNM}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USRNM}"]
      interval: 5s
      retries: 5
      timeout: 5s

  ffiec-institutions:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
