services:
  postgres-db-ffiec:
    image: postgres
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: ${DB_USRNM}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    command: postgres -c max_wal_size=4GB -c min_wal_size=1GB
    volumes:
      - ffiec_postgres_data:/var/lib/postgresql/data
    networks:
      - ffiec-transformations
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USRNM}"]
      interval: 5s
      retries: 5
      timeout: 5s

  ffiec-institutions:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-db-ffiec:
        condition: service_healthy
    networks:
      - ffiec-transformations

networks:
  ffiec-transformations:
    driver: bridge
  
volumes:
  ffiec_postgres_data:
    driver: local
